# -*- coding: utf-8 -*-
import AutoDecode
import prepareString

#Example messages
msg=  'egyptiantempleswerebuilttocommemoratethepharaohsandtosupportthecentralfunctionsoftheirreligiongivingofferingstothegodsreenactingtheirmythologicalinteractionsthroughfestivalsandwardingofftheforcesofchaosritualsitwasbelievedinvokedthedivinepresencesustainedthegodandenabledittocontinuetoupholdthedivineorderoftheuniversetempleswereimportantreligioussitesforallclassesofegyptianseventhoughmostpeoplewereforbiddenfromenteringtheirmostsacredareastheyareamongthelargestandmostenduringexamplesofegyptianarchitecturewiththeirelementsarrangedanddecoratedaccordingtocomplexpatternsofreligioussymbolismalargetemplecouldownsizabletractsoflandandemploythousandsoflaymentosupplyitsneedssometemplessuchasabusimbelhavebecometouristattractionsthatcontributesignificantlytothemodernegyptianeconomyegyptologistscontinuetostudythesurvivingtemplesfortheirinvaluablesourcesofinformationaboutancientegyptiansociety'
msg1 = 'aeuropeaninnovationcastlesoriginatedintheandcenturiesafterthefallofthecarolingianempireresultedinitsterritorybeingdividedamongindividuallordsandprinces'
msg2 = 'althoughgunpowderwasintroducedtoeuropeinthecenturyitdidnotsignificantlyaffectcastlebuildinguntilthecenturywhenartillerybecamepowerfulenoughtobreakthroughstonewalls'
msg3 = 'intheunitedstatesthestandardcellisequippedwitheitheraledgeorasteelbedsteadthatholdsamattressaconstructedofweldedputativelystainlesssteelisalsoprovidedbarstypifyolderjailswhileneweroneshavedoorsthattypicallyfeatureasmallsafetyglasswindowandoftenametalflapthatcanbeopenedtoservemeals'
msg4 = 'thesunisthestaratthecenterofthesolarsystemitisanearlyperfectsphereofhotplasmawithinternalconvectivemotionthatgeneratesamagneticfieldviaadynamoprocess'
msg5 = 'dsdroxfijvdiysbanqaltaimxvbdmbgassaqrtrtcggxjmmtqcipjsbaqpdrsdimsduambcqcmsaqdrsdmrjnsbagciytcyasbcsmqxkscicgxrsrcqacogasjpasaqhdiasbakgcdisawsjncmdkbaqharrcyae'
msg6 = 'instatisticslinearregressionisalinearapproachformodelingtherelationshipbetweenascalardependentvariableyandoneormoreexplanatoryvariablesorindependentvariablesdenotedxthecaseofoneexplanatoryvariableiscalledsimplelinearregression'
msg7 = 'thisdogisfarawayfromhomeweshouldtrytofindhisowners'
msg8 = 'thisdogisfarawayfromhomeweshouldtrytofindhisownersmaybetheywillevengiveussomereward'
msg9 = 'thisdogisfarawayfromhomeweshouldtrytofindhisownersmaybetheywillevengiveussomerewardwiththemoneywegetwecouldbuyourowndog'
msg10 = 'thisdogisfarawayfromhomeweshouldtrytofindhisownersmaybetheywillevengiveussomerewardwiththemoneywegetwecouldbuyourowndogithinktakingcareforadogwillstrenghtenourrelationshipaswell'

msg11 = 'vhišojeprineselvelikonovegaznanjašolalsejenamrečvzelouglednišolimamamujeprineslahraneinpijačekerpasevedanihoteloditijeodšelboljkmalukonivečvedelkolikodenarjajeimelprisebisejeposvetovalzdirektorjem'

msg12 = 'abcčdefghciejdčdkiejcgfhadlmcafčdkdhlkchcncodecpkčfhfbglčeljmjlčrljčdbslhfecbglčhlkdechlnlšclmcecpkčdphcjlpalmcčmčdjgdhjdgofgacgtgfšbjmtadnlnjdhcmhlutbedntščdacjlčbglčeljmjlčrdjčdblmcafčdhcncodlalmcč'


#Select a message from a messages above, or create your own message as in the example below. 

unprepared = "On GitHub, saved changes are called commits. Each commit has an associated commit message, which is a description explaining why a particular change was made. Commit messages capture the history of your changes, so other contributors can understand what you’ve done and why."
prepared = prepareString.PrepareString(unprepared)

########################################
#This message wil be encoded and decoded
m=msg12
########################################

#Creates an encoding key for encoding a custom massage
key="".join(AutoDecode.shuffled(AutoDecode.alphabet))
#Encodes a custom message with a given key
encoded = AutoDecode.encode(m,key)


#Outputs of user inputs and decoding process
print("Original: ",m)
print("key: ",key)
print("Encoded: ",encoded)
print("Decoded: ",AutoDecode.decode_subst(m))